blank_issues_enabled: false
contact_links:
  - name: Security vulnerability disclosure
    url: https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities
    about: Please avoid public issues for vulnerabilities.
